### ISSUE TITLE
Allow std::atomic usage of QuantityPoint with gcc-9

### ISSUE THREAD

**Issue by avrahamshukron** [aurora-opensource/au#119]
It appears to be impossible to define `std::atomic` variable of a `QuantityPoint` when using gcc-9 or older version.

Example:

```cpp
#include <atomic>

using Kelvins = au::QuantityPointU32<au::Kelvins>;

int main()
{
    std::atomic<Kelvins> m_atomic_temp;
}
```

Output:
```
In function 'int main()':
<source>:5023:26: error: use of deleted function 'constexpr std::atomic<_Tp>::atomic() [with _Tp = au::QuantityPoint<au::Kelvins, unsigned int>]'
 5023 |     std::atomic<Kelvins> m_atomic_temp;
      |                          ^~~~~~~~~~~~~
In file included from <source>:5017:
/opt/compiler-explorer/gcc-9.5.0/include/c++/9.5.0/atomic:198:7: note: 'constexpr std::atomic<_Tp>::atomic() noexcept [with _Tp = au::QuantityPoint<au::Kelvins, unsigned int>]' is implicitly deleted because its exception-specification does not match the implicit exception-specification ''
  198 |       atomic() noexcept = default;
      |       ^~~~~~
```

In godbolt.org: https://godbolt.org/z/beG9Tfee3

On gcc-10 and up the above code compiles just fine.

**Comment by chiphogg** [comment]
I can reproduce on godbolt.  Looks like #120 would fix it.  @avrahamshukron, can you confirm?

And are there other `std::atomic` test cases you want to double check before we land #120?

**Comment by avrahamshukron** [comment]
I can confirm that #120 fixes the problem.
Currently I can only imagine atomic Quantity and atomic QuantityPoint, which are both covered, so I'm OK with #120 as-is.
Thank you for the very quick reply!
