### ISSUE TITLE
Windows MSVC C++17 CMake/Ninja Compile Errors on prebuilt header

### ISSUE THREAD

**Issue by connorjak** [aurora-opensource/au#143]
Using prebuilt https://aurora-opensource.github.io/au/0.3.2/au_noio.hh, I included the file in my project and I get this block of errors. 
```
C:\Users\conno\Documents\SC\Platform\Compute_Server\externals\Au\au.h(1247): error C2672: 'au::detail::are_consecutive_elements_in_order_for': no matching overloaded function found
  C:\Users\conno\Documents\SC\Platform\Compute_Server\externals\Au/au.h(1247): note: see reference to class template instantiation 'au::AreElementsInOrder<Pack,Pack<Ts...>>' being compiled
C:\Users\conno\Documents\SC\Platform\Compute_Server\externals\Au\au.h(1247): error C3207: 'au::detail::are_consecutive_elements_in_order_for': invalid template argument for 'Pack', class template expected
  C:\Users\conno\Documents\SC\Platform\Compute_Server\externals\Au/au.h(1229): note: see declaration of 'au::detail::are_consecutive_elements_in_order_for'
C:\Users\conno\Documents\SC\Platform\Compute_Server\externals\Au\au.h(1247): error C2977: 'au::detail::are_consecutive_elements_in_order_for': too many template arguments
  C:\Users\conno\Documents\SC\Platform\Compute_Server\externals\Au/au.h(1219): note: see declaration of 'au::detail::are_consecutive_elements_in_order_for'
C:\Users\conno\Documents\SC\Platform\Compute_Server\externals\Au\au.h(1261): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'std::array<bool,sizeof...(Ts)>'
  C:\Users\conno\Documents\SC\Platform\Compute_Server\externals\Au/au.h(1261): note: The target type has no constructors
  C:\Users\conno\Documents\SC\Platform\Compute_Server\externals\Au/au.h(1261): note: see reference to class template instantiation 'au::AreAllPowersNonzero<Pack,Pack<Ts...>>' being compiled
```

I am unable to figure out what the cause might be. It seems this may be the only problem with Au on this compiler, though, so it's valuable to know a fix or workaround.

### Compile info:
- Windows 10
- RelWithDebInfo Configuration
- Toolchain: msvc_x64_64
- MSVC v142 - VS 2019
- cl version 14.29.30133
- CMake build through Visual Studio's CMake support (Ninja)
- CMake configuration:
```cmake
set(CMAKE_CXX_STANDARD 17) 
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```

**Comment by connorjak** [comment]
As more background, I'm interested in using this library in my aerospace engineering analysis and design platform. We're aiming for cross-platform Windows/Linux/MacOS, and using Unreal Engine as our graphics and interaction client. Unreal is still limited to C++17 so I'm unable to use [mp-units](https://github.com/mpusz/mp-units), so the main deciding features for me for using Au over [nholthaus](https://github.com/nholthaus/units/commits?author=nholthaus) are the (probably) better compile time and (most likely) better compilation error readability.

**Comment by chiphogg** [comment]
Thanks very much for bringing this to our attention, and for explaining your use case!  This will be our first experience with using Au on a Windows platform, so bear with us as we train this new muscle.  :slightly_smiling_face: 

I've given some thought to how we can solve this category of problem robustly, and filed #144 to track that work.  It's hard for me to say exactly how it will go until I start digging in: both in terms of setting up the tooling, and in terms of investigating this specific error.  I hope we can find a fix.

If we can get over this hurdle, then yes, I do expect Au will have the clear advantages over nholthaus that you expect.  There [are a lot of other advantages](https://aurora-opensource.github.io/au/main/alternatives/#library-features), too, which I think you'll appreciate.  The key ones I'd highlight include:

- Much better conversion safety
- On-the-fly composability of units and prefixes
- Unit-safe interfaces
- [`ZERO`](https://aurora-opensource.github.io/au/main/discussion/concepts/zero/), to make it easier to work with signs

The main advantages of nholthaus over Au are:

- They already have user-defined literals included.  (With Au, you'd have to define your own, which is what we've done internally at Aurora.  Our rough plan for Au is to come up with something that scales better and is more flexible than UDLs; see #43.)
- They support decibels.  (We would like to do this someday, but are very unlikely to work on it any time soon; see #41.)

I can't make any promises as to when I'll get to dig into the MSVC compiler error, or whether we'll be able to work around it, but I hope it's helpful to at least be able to see what the plan is.

**Comment by connorjak** [comment]
I just tried the same project CMake compile but on Linux, with WSL2 Ubuntu / gcc, and the library works great! This is definitely an issue specific to MSVC.

The row in this table on Wikipedia has some more specific information about my exact compiler version (VS 2019 16.11.25): https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#:~:text=visual%20studio%202019%20version%2016.11.24

**Comment by chiphogg** [comment]
I installed MSVC on my Windows box at home.  I think I figured out all the compiler errors.

Could you check and see if this fixes it?  You can see our [development setup](https://aurora-opensource.github.io/au/main/develop/) guide to get set up.  Once you do, you can run `bazel build //:au_noio_hh`, and the file will be produced in `bazel-bin/docs/au_noio.hh`.  (I tried simply attaching it, but github does not like `.hh` files.  I can always rename it to `.txt` if you can't generate it on your own, though!)

**Comment by chiphogg** [comment]
Sorry --- to be clear, by "this", I meant PR #146.  :stuck_out_tongue:

**Comment by chiphogg** [comment]
Since the PR is now approved, I decided to rename it to `.txt` so I could attach it and make it easier for you.

[au_noio.txt](https://github.com/aurora-opensource/au/files/11984411/au_noio.txt)

**Comment by connorjak** [comment]
Changes above for 0.3.2-11-g9e8b6e0 have fixed the compile errors in MSVC in my project as well. Thanks for the quick work!

**Comment by chiphogg** [comment]
@connorjak, I could use a little help with a follow-up item.

We now have our first automated CI builds for Windows, using the [windows-2019](https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md) and [windows-2022](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md) images.  I'd like to document which versions of MSVC we support, in a way that MSVC users will understand.  However, I'm really confused about just which versions we are running!

In your original post, you listed at least 3 items that could be construed (to my ignorant eye) as "the version of MSVC":

- MSVC v142
- VS 2019
- cl version 14.29.30133

So my questions are:

1. Which of these would an MSVC user most likely be looking for?
2. How do I find the corresponding version number from my CI job's logs?

So far, the only one I can find is the cl version: it's `19.29.30151` for `windows-2019`, and `19.35.32217.1` for `windows-2022`. 
 (Here's [an example run](https://github.com/aurora-opensource/au/actions/runs/5672849976), although I imagine you might not have access to drill down into the logs.  If you don't, I can copy-paste the relevant parts if it'd be helpful.)

You've already been a great help in bringing the Windows issues to our attention.  If you're able to give me some further guidance here, then I'll be able to make our MSVC support more formal and official, and help out other users.  Thanks!

**Comment by connorjak** [comment]
From what I remember, VS 2019 vs VS 2022 is just referring to the IDE, which has functionality for many languages. MSVC version is referring to the Microsoft Visual C build tools version, and `cl` is the compiler inside those build tools. For matters of compiler compatibility, I think there are usually only visible changes to compiler behavior in version changes of MSVC `v19.xx`. Compiler Explorer https://godbolt.org/ has MSVC compiler versions arranged with that as the determining factor for differences in compiler behavior. There are some more details with ABI compatibility but because this library is header-only there should not be a problem.

The naming conventions are quite confusing but lately the _MSC_VER 3rd digit has been incrementing with VS major version number, and _MSC_VER 4th digit has been (mostly) matching VS minor version. From those CI images, it appears the 2019 one is set up with VS 2019 - 16.11 (_MSC_VER 1929), and 2022 has VS 2022 - 17.6 (_MSC_VER 1936).

The `_MSC_VER` macro is set by the compiler to mark this version. https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B.

**Comment by connorjak** [comment]
More info on MSVC C++ standards compliance changes through versions: https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170

**Comment by chiphogg** [comment]
That's really helpful, thanks!  I think following the godbolt schema will be the best option.  Much appreciated!
