### ISSUE TITLE
Where are `au.hh` and `au_noio.hh`?

### ISSUE THREAD

**Issue by jaskij** [aurora-opensource/au#189]
Your documentation states

> We provide pre-generated single-file versions of the library, automatically generated from the latest commit in the repo:

but I have been unable to find them? They're not added as assets to GH releases, and don't seem to exist in the repository itself.

**Comment by chiphogg** [comment]
They can be found in our documentation website, on the [installation page](https://aurora-opensource.github.io/au/main/install/#pre-built-single-file).

**Comment by jaskij** [comment]
Argh, those bullet points are links. Thanks, I completely failed to notice them as such.

**Comment by chiphogg** [comment]
Actually, you uncovered a serious accessibility hole in our doc website!  Best practices suggest underlining links, so they're easier to distinguish.  We'll land a PR shortly to fix this.
