### ISSUE TITLE
Support QuantityPoint in math functions like round_in, round_as

### ISSUE THREAD

**Issue by avrahamshukron** [aurora-opensource/au#221]
It would be really useful to be able to use all math functions on `QuantityPoint` just like Quantity.
In general, `QuantityPoint` should be a first-class type.

**Comment by avrahamshukron** [comment]
Hi @chiphogg do you have any estimation for possible timeline for a fix?
I'm considering whether to develop some kind of work-around or simply define our `Temperature` as `Quantity` instead of `QuantityPoint` until the issue is fixed.

**Comment by chiphogg** [comment]
Thanks for your patience and for the ping!  I will try to knock this out this week.

**Comment by chiphogg** [comment]
This should be ready to go now on main.  Enjoy!
