### ISSUE TITLE
Incorrect conversion result from Kelvins to Celsius

### ISSUE THREAD

**Issue by avrahamshukron** [aurora-opensource/au#222]
We define our canonical representation of temperature as U32 Milli-Kelvins:
```cpp
/**
 * Our canonical Temperature unit is milli-kelvin stored in uint32.
 * uint32_t holds the relevant range of temperatures in mK while providing good resolution to our needs.
 */
using Temperature = au::QuantityPointU32<au::Milli<au::Kelvins>>;
```

Interestingly, the following static_assert fails:
```cpp
constexpr auto millikelvins = au::milli(au::kelvins_pt);
constexpr Temperature ABSOLUTE_ZERO = millikelvins(0);

// We expect to lose the `.15` here due to integer being used, but `ABSOLUTE_ZERO` should be `-273C`.
static_assert(ABSOLUTE_ZERO.in<int>(au::celsius_pt) == -273); // Fails to compile:  '4294694 == -273'
```

It doesn't fail if I ditch my predefined `QuantityPoint` and rather just use the maker directly:
```cpp
static_assert(millikelvins(0).in<int>(au::celsius_pt) == -273); // compiles, the world make sense again.
```

So clearly something in forcing the combination of mK and U32 does something here, and I'm not sure what.
It looks like integer underflow, buy would any subtraction take place in this conversion?
In order to go from mK to C all is needed is `(mK+273150) / 1000`

So I guess my question is what is going on, and how can I avoid it considering that I care about the actual representation of temperature since the project is an embedded device, so size matters.

Thanks.

**Comment by chiphogg** [comment]
> So clearly something in forcing the combination of mK and U32 does something here, and I'm not sure what. It looks like integer underflow, buy would any subtraction take place in this conversion? In order to go from mK to C all is needed is `(mK+273150) / 1000`

I think that's actually the formula to convert from mC to K?  I had to stare at it a bunch to be sure.  I always get these mixed up.  (It's why I wrote the library!  :sweat_smile:)

That said, your code examples all look right to me.

> So I guess my question is what is going on, and how can I avoid it considering that I care about the actual representation of temperature since the project is an embedded device, so size matters.

What's going on is that `QuantityPoint` conversion involves subtracting the origin displacement.  Unfortunately, we currently just subtract it from whatever our stored value is.  So if the original value is unsigned, this will be a subtraction between unsigned and signed.  I _believe_ C++ will apply the (rather byzantine) _type promotion_ rules to decide what type to use to carry out the computation.  For our purposes, I think it's basically "bigger type wins, but ties go to the unsigned type".

Here's a [godbolt playground](https://godbolt.org/z/EM1xj6jvq).  When we subtract signed from unsigned, if they're the same size, we get the unsigned type, but if the signed type is bigger then we get the signed type instead.

I think the solution is to eagerly cast each participant in the subtraction to the destination type.  Does #223 solve the problem for you?  (I believe it's correct, but in making it, I discovered #224 which will have to get solved first.)

**Comment by avrahamshukron** [comment]
> I think that's actually the formula to convert from mC to K? I had to stare at it a bunch to be sure. I always get these mixed up. (It's why I wrote the library! 😅)

Yep, that's absolutely right :man_facepalming: I definitely need a units library :sweat_smile: 

I can confirm that with your patch applied the issue goes away.
Thank you so much for the (insanely) quick response!

**Comment by chiphogg** [comment]
No prob!  In this case, the act of root causing was basically equivalent to producing a test and a fix.

Now if we could just [land code again](https://github.com/aurora-opensource/au/issues/224)... :smile:
