### ISSUE TITLE
Consider making Quantity contructor public 

### ISSUE THREAD

**Issue by StefanoD** [aurora-opensource/au#230]
Hi,
first, thank you for this great library!
We are currently using nholthaus units library and consider to switch to this library.
While playing around with Au, I stumbled into the cumbersome `QuantityMaker`. While I see the sense to use this as a replacement for UDL, I am actually missing the constructor for `Quantity`, because we have much code with `microliters<double>(1)` and so on and porting to Au, which forces to use the `QuantityMaker`, will make it cumbersome. Also the acceptance to this new library might suffer from my team collegues.

To understand better my problem:
We actually have wrappers to the nholthaus units library:

```cpp
namespace IC::Core::Units { // This is our own namespace

// We wrap everything with double, because this is universal
using Meters = units::length::meters<double>;
using Centimeters = units::length::centimeters<double>; 
using Millimeters = units::length::millimeters<double>; 
using Micrometers = units::length::micrometers<double>;
using Nanometers = units::length::nanometers<double>; 

}
```
We did this this way, because we anticipated that we might switch to another units library in the future and tried to hide the implementation details and my port would be:

```cpp
namespace IC::Core::Units {
using Meters = au::QuantityD<au::Meters>;
constexpr auto meters = au::meters;
constexpr auto second = au::second;
constexpr auto seconds = au::seconds;

using MetersPerSecond = au::QuantityD<decltype(au::Meters{} / au::Seconds{})>;
constexpr auto meters_per_second = (au::meters / au::second);
}
```

Now I would like to write code like:

```cpp
IC::Core::Units::Meters m1(2); // Does not compile, because of private constructor
IC::Core::Units::Meters m2 = meters(2);
```

I think that `m1` is as legit ad `m2`.
Could you please make the private constructor public? This would make porting easier and also writing code would be less cumbersome.

Thanks.

**Comment by chiphogg** [comment]
I wanted to add a couple of resources for posterity, in case other people stumble across this issue.  First, there's [the "unit safety" section](https://aurora-opensource.github.io/au/main/tutorial/101-quantity-makers/#our-goal-unit-safety) of our 101 tutorial, which explains the concept and importance of unit safety.  Second, see mpusz/mp-units#434 for a really interesting undesired consequence of making the `Quantity` constructor public, which I hadn't thought of before.

Thanks for raising the issue!
