### ISSUE TITLE
Update GitHub actions versions

### ISSUE THREAD

**Issue by chiphogg** [aurora-opensource/au#260]
We're getting a bunch of errors (e.g., because `checkout` uses node12, which is deprecated).  We should consider batching the security reviews.

**Comment by timhirsh** [comment]
Good call.  We already completed a review for a newer version, so #261 should bump us to node20.

**Comment by timhirsh** [comment]
Remaining deprecation warnings:
- `ilammy/msvc-dev-cmd@cec98b9d092141f74527d0afa6feb2af698cfe89` ([run](https://github.com/aurora-opensource/au/actions/runs/9877004774?pr=261))
- `viperproject/check-license-header@971caaf7d1641bb2c6a49acd06b018a5ce51ad6e` ([run](https://github.com/aurora-opensource/au/actions/runs/9877004778?pr=261))
- `zgosalvez/github-actions-ensure-sha-pinned-actions@af2eb3226618e2494e3d9084f515ad6dcf16e229` ([run](https://github.com/aurora-opensource/au/actions/runs/9877004773?pr=261))

I'll kick off a review for these as well.

**Comment by chiphogg** [comment]
> Remaining deprecation warnings:
> 
> * `ilammy/msvc-dev-cmd@cec98b9d092141f74527d0afa6feb2af698cfe89` ([run](https://github.com/aurora-opensource/au/actions/runs/9877004774?pr=261))
> * `viperproject/check-license-header@971caaf7d1641bb2c6a49acd06b018a5ce51ad6e` ([run](https://github.com/aurora-opensource/au/actions/runs/9877004778?pr=261))
> * `zgosalvez/github-actions-ensure-sha-pinned-actions@af2eb3226618e2494e3d9084f515ad6dcf16e229` ([run](https://github.com/aurora-opensource/au/actions/runs/9877004773?pr=261))
> 
> I'll kick off a review for these as well.

Thanks @timhirsh !  Any updates on the review for these?

**Comment by timhirsh** [comment]
Yup, PR's incoming ☝️ 

We also need `actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566`, so that'll be the last one.
