### ISSUE TITLE
MSVC 19.35 CI isn't fixed-version; updates to latest

### ISSUE THREAD

**Issue by connorjak** [aurora-opensource/au#283]
The latest runs of the MSVC 19.35 workflow are using 19.40. It is probably good to keep testing with latest MSVC but the CI should be relabeled. Could call it MSVC 2022 because it's on the windows-2022 runner.

- https://github.com/aurora-opensource/au/actions/runs/10061250249/job/27810846466#step:6:55
- https://github.com/aurora-opensource/au/actions/workflows/msvc-x64-19-35-32217-1.yml

The MSVC 19.29 workflow is staying on that compiler version properly, but I assume this is because the windows-2019 runner is no longer getting major compiler version updates.
- https://github.com/aurora-opensource/au/actions/runs/10255370911/job/28372173649#step:6:58
- https://github.com/aurora-opensource/au/blob/main/.github/workflows/msvc-x64-19-29-30151.yml

**Comment by chiphogg** [comment]
Very well spotted!  I admit that I find MSVC compiler numbers and versions very confusing.

I like your recommendation for "MSVC 2022".  I'll also go with "MSVC 2019" for the other one, for consistency.
