### ISSUE TITLE
Document vcpkg install

### ISSUE THREAD

**Issue by andre-nguyen** [aurora-opensource/au#301]
Hey @chiphogg 

Guess we can change the line below now that this got merged 🥳 https://github.com/microsoft/vcpkg/pull/41119

https://github.com/aurora-opensource/au/blob/fb0384882c8f60792e8a031dd88801609d500920/docs/install.md?plain=1#L51

I don't mind writing it in but I wonder what you would put in the decision diagram?

**Comment by chiphogg** [comment]
Very exciting!  And by what appears to be a huge coincidence, it landed on the **exact same day** as conan support (conan-io/conan-center-index#25447).  :open_mouth: 

I should probably give the whole installation page a once-over.  I think I can get to that by this weekend.
