### ISSUE TITLE
A folder, constants, disappeared when I run "git checkout 0.3.5".

### ISSUE THREAD

**Issue by 1040170566** [aurora-opensource/au#344]
I want to install this library with cmake. The tutorial teaches me that, and I succeed. However, I can't find the "constants" folder. I don't know why. In fact, I have found that folder before I run the checkout.

**Comment by chiphogg** [comment]
Welcome!

The `constants` folder is newer than the 0.3.5 release.  While the _core machinery_ for `Constant<...>` [_did exist_ in 0.3.5](https://aurora-opensource.github.io/au/0.3.5/reference/constant/), library-provided values are a new feature that was only added within the last week or so (see #90).

**Comment by 1040170566** [comment]
Thank you very much!

**Comment by chiphogg** [comment]
You're welcome :slightly_smiling_face:
