### ISSUE TITLE
Support constants

### ISSUE THREAD

**Issue by chiphogg** [aurora-opensource/au#90]
In some sense, we can already do this.

```cpp
constexpr auto RAD = radians(1);
```

However, this brings `int` into the equation, via the `1`.  This could affect the arithmetic of the underlying Reps in some equations where it gets used.  It could also run afoul of our guards against integer division.

It would be nice if we could express constants _solely in the realm of dimensions and magnitudes_.  We might need to make a new type template, such as `Constant`.  It would probably be a "monovalue type" (in the nomenclature introduced in #88).  Perhaps something like this:

```cpp
constexpr auto RAD = make_constant(Radians{});
```

Alternatively: maybe a "constant" is just an instance of a _unit_?  We would need to enable multiplying and dividing a quantity by a unit, if so.  Then we would write:

```cpp
constexpr auto RAD = Radians{};
```

It's interesting to imagine how this would look with other constants.  Consider something like $E = mc^2$.  We might write `kilo(grams)(10.0) * squared(C)`... and the result might be labeled as `10 kg * c^2`.  Of course we could also apply `.as(joules)` to the result to get a more familiar unit.

This is an intriguing idea worth exploring more later.

**Comment by chiphogg** [comment]
Having thought more about this: no, a constant should _not_ just be an instance of a unit.  A "unit" could be basically any type, so we'd need SFINAE, which would be expensive.  This argues in favor of using a `Constant` template.

It's probably still good to keep this template as a [monovalue type](https://aurora-opensource.github.io/au/reference/detail/monovalue_types/), and use a labeled unit.

**Comment by chiphogg** [comment]
Here's a running checklist for what it would take to call this feature "done".  (I'll check things off as they're implemented locally in my client, rather than on remote.)

- [ ] Multiplication and division
   - [ ] Regular numbers
   - [ ] `Quantity`
   - [ ] `Magnitude`
   - [ ] Other `Constant`
   - [ ] `QuantityMaker`
   - [ ] `SingularNameFor`
   - [ ] `QuantityPoint` (`= delete`)
   - [ ] `QuantityPointMaker` (`= delete`)
- [ ] Explicit conversions to `Quantity`
   - [ ] `.as<T>()`: initialize with `T{1}` in units of the constant
   - [ ] `.as<T>(unit)`: choose unit-and-rep
      - [ ] Exact representability checks (no "safety surface" heuristics)
   - [ ] `.coerce_as<T>(unit)`: choose unit-and-rep, ignore safety checks
- [ ] Explicit unit conversions to raw number
   - [ ] `.in<T>(unit)`: choose unit-and-rep
      - [ ] Exact representability checks (no "safety surface" heuristics)
   - [ ] `.coerce_in<T>(unit)`: choose unit-and-rep, ignore safety checks
- [ ] `make_constant(...)`
- [ ] Implicit conversions to `Quantity`
- [ ] Presentation
   - [ ] How to name constants?  `c` vs. `C` vs. `SPEED_OF_LIGHT`; `h` (or `h_bar`) vs. `H` (or `H_BAR`) vs. `PLANCK_CONSTANT`; etc.
   - [ ] Use `constants` sub-namespace?
   - [ ] Update single-file script to include constants
- [ ] Documentation
   - [ ] Reference page
   - [ ] Update single-file section of installation docs
   - [ ] Alternatives page

**Comment by geoffviola** [comment]
We may want to add some documentation for how to add a new constant, after we settle on the presentation.
